// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ5H4PfDJuGuue1SpfiS8sSvUi462xG7w',
    appId: '1:1907668067:web:6029989e7d842b5b72f456',
    messagingSenderId: '1907668067',
    projectId: 'clonetrip2025',
    authDomain: 'clonetrip2025.firebaseapp.com',
    storageBucket: 'clonetrip2025.firebasestorage.app',
    measurementId: 'G-NV21LJ6FPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Zg_5oqLhqAR2VK5R4hcUnjXpGdiiIhk',
    appId: '1:1907668067:android:567b92e8cf824ab772f456',
    messagingSenderId: '1907668067',
    projectId: 'clonetrip2025',
    storageBucket: 'clonetrip2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXw3lLYn4IHIjXwiXVEYXnuhTDknmOsuw',
    appId: '1:1907668067:ios:41c41a6feb28460672f456',
    messagingSenderId: '1907668067',
    projectId: 'clonetrip2025',
    storageBucket: 'clonetrip2025.firebasestorage.app',
    iosBundleId: 'com.example.clonetrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXw3lLYn4IHIjXwiXVEYXnuhTDknmOsuw',
    appId: '1:1907668067:ios:41c41a6feb28460672f456',
    messagingSenderId: '1907668067',
    projectId: 'clonetrip2025',
    storageBucket: 'clonetrip2025.firebasestorage.app',
    iosBundleId: 'com.example.clonetrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ5H4PfDJuGuue1SpfiS8sSvUi462xG7w',
    appId: '1:1907668067:web:227a76a82d1e2c8472f456',
    messagingSenderId: '1907668067',
    projectId: 'clonetrip2025',
    authDomain: 'clonetrip2025.firebaseapp.com',
    storageBucket: 'clonetrip2025.firebasestorage.app',
    measurementId: 'G-9T68BJWRRB',
  );

}